
// FIX: Corrected import path for types
import { Product } from '../types';

export const productDatabase: Product[] = [
  {
    sku: 'SW-0401-MST',
    name: '4x1 4K HDBaseT Presentation Switcher',
    category: 'Presentation Switcher',
    description: 'A simple 4-input switcher with HDBaseT and mirrored HDMI outputs. Ideal for basic meeting rooms.',
    dealerPrice: 450,
    msrp: 900,
    tags: ['switcher', 'hdbaset', 'bronze'],
    connections: { hdmiIn: 2, usbC: 1, hdbasetOut: 1, hdmiOut: 1 },
    control: { rs232: true, ir: true, cec: true },
  },
  {
    sku: 'APO-VX20-UC',
    name: 'Apollo VX20 All-in-One Video Bar',
    category: 'Unified Communications',
    description: 'An all-in-one video bar with 4K camera, beamforming microphone array, and stereo speakers.',
    dealerPrice: 800,
    msrp: 1600,
    tags: ['uc', 'video bar', 'byom', 'bronze'],
    connections: { usbC: 1 },
    audio: { micIn: true },
  },
  {
    sku: 'APO-210-UC',
    name: 'Apollo 210 UC Switcher',
    category: 'Unified Communications',
    description: 'Advanced UC switcher with USB-C, HDMI, and HDBaseT. Supports BYOM and dual displays.',
    dealerPrice: 1200,
    msrp: 2400,
    tags: ['uc', 'switcher', 'byom', 'silver'],
    compatibleReceivers: ['APO-RX1'],
    connections: { hdmiIn: 2, usbC: 1, hdbasetOut: 1, lanPassThrough: true },
    control: { rs232: true, cec: true },
  },
  {
    sku: 'APO-RX1',
    name: 'Apollo HDBaseT 3.0 Receiver',
    category: 'Receiver',
    description: 'HDBaseT 3.0 receiver for Apollo series switchers. Supports 4K60 and USB.',
    dealerPrice: 300,
    msrp: 600,
    tags: ['receiver', 'hdbaset', 'silver'],
  },
  {
    sku: 'MX-0403-H3-MST',
    name: '4x3 HDBaseT 3.0 Matrix Switcher Kit',
    category: 'Matrix Switcher',
    description: '4-input, 3-output HDBaseT 3.0 matrix with USB-C and HDMI inputs. Includes 2 receivers.',
    dealerPrice: 1800,
    msrp: 3600,
    tags: ['matrix', 'hdbaset', 'silver', 'kit'],
    kitContents: ['RX-H3-MST (x2)'],
    compatibleReceivers: ['RX-H3-MST'],
    connections: { hdmiIn: 2, usbC: 1, hdbasetOut: 2, hdmiOut: 1 },
    control: { rs232: true, ir: true },
  },
  {
    sku: 'CAM-210-PTZ',
    name: '4K AI PTZ Camera',
    category: 'Camera',
    description: 'A 4K PTZ camera with auto-framing and auto-tracking AI features.',
    dealerPrice: 750,
    msrp: 1500,
    tags: ['camera', 'ptz', 'silver', 'gold'],
    connections: { hdmiOut: 1 },
    control: { rs232: true },
  },
  {
    sku: 'HALO 80',
    name: 'HALO 80 Conference Speakerphone',
    category: 'Audio',
    description: 'USB and Bluetooth speakerphone with 4-mic array and 360-degree pickup.',
    dealerPrice: 350,
    msrp: 700,
    tags: ['audio', 'microphone', 'speakerphone', 'silver'],
    audio: { micIn: true },
  },
  {
    sku: 'EX-100-KVM',
    name: '100m HDBaseT 2.0 KVM Extender',
    category: 'Extender',
    description: 'HDBaseT 2.0 extender kit supporting 4K video, audio, control, and USB 2.0 up to 100m.',
    dealerPrice: 400,
    msrp: 800,
    tags: ['extender', 'kvm', 'hdbaset'],
    connections: { hdmiIn: 1, hdmiOut: 1, lanPassThrough: true },
    control: { rs232: true, ir: true },
  },
  {
    sku: 'EX-40-KVM-5K',
    name: '40m HDBaseT 3.0 KVM Extender (5K)',
    category: 'Extender',
    description: 'Extends uncompressed 5K/30Hz or 4K/60Hz video, audio, Ethernet, control and USB 2.0 up to 40m/131ft.',
    dealerPrice: 480,
    msrp: 960,
    tags: ['extender', 'kvm', 'hdbaset', 'hdbaset 3.0', 'silver'],
    connections: { hdmiIn: 1, hdmiOut: 1 },
    control: { rs232: true, ir: true },
  },
    {
      sku: 'MX-1007-HYB',
      name: '10x7 Hybrid Matrix Switcher',
      category: 'Matrix Switcher',
      description: 'High-end hybrid matrix with 8 HDBaseT 3.0 inputs/outputs, 2 AVoIP inputs, and a dedicated Dante audio matrix.',
      dealerPrice: 9000,
      msrp: 18000,
      tags: ['matrix', 'hdbaset', 'avoip', 'dante', 'gold'],
      connections: { hdbasetIn: 8, hdbasetOut: 5, hdmiOut: 2 },
      audio: { analogIn: 4, analogOut: 4, dante: 'dedicated' },
      avoip: { series: 500 },
  },
  {
    sku: 'NHD-400-E-TX',
    name: 'NetworkHD 400 Series Encoder',
    category: 'AVoIP',
    description: '4K HDR Encoder for the 400 series.',
    dealerPrice: 450,
    msrp: 900,
    tags: ['avoip', 'encoder'],
    avoip: { series: 400 },
    eol: true, // This product is End-of-Life
  },
  {
      sku: 'NHD-500-TX',
      name: 'NetworkHD 500 Series AVoIP Encoder',
      category: 'AVoIP',
      description: '4K60 AVoIP encoder with USB 2.0 and optional software-enabled Dante.',
      dealerPrice: 526,
      msrp: 1052,
      tags: ['avoip', 'encoder', 'gold'],
      audio: { dante: 'software' },
      avoip: { series: 500, multiview: 'requires_switcher' },
  },
  {
    sku: 'NHD-500-RX',
    name: 'NetworkHD 500 Series AVoIP Decoder',
    category: 'AVoIP',
    description: '4K60 AVoIP decoder with USB 2.0 and optional software-enabled Dante.',
    dealerPrice: 526,
    msrp: 1052,
    tags: ['avoip', 'decoder', 'gold'],
    audio: { dante: 'software' },
    avoip: { series: 500, multiview: 'requires_switcher' },
  },
  {
    sku: 'NHD-150-TX',
    name: 'NetworkHD 150 Series Encoder',
    category: 'AVoIP',
    description: '1080p AVoIP encoder for the 150 series, ideal for multiview applications.',
    dealerPrice: 300,
    msrp: 600,
    tags: ['avoip', 'encoder', 'multiview'],
    avoip: { series: 150 },
  },
  {
    sku: 'NHD-150-RX',
    name: 'NetworkHD 150 Series Decoder/Controller',
    category: 'AVoIP',
    description: '1080p AVoIP decoder with native multiview processing for up to 2x2 video walls.',
    dealerPrice: 500,
    msrp: 1000,
    tags: ['avoip', 'decoder', 'multiview'],
    avoip: { series: 150, multiview: 'native' },
  },
  {
    sku: 'SW-0401-MV-HDBT',
    name: '4x1 Multiview Switcher with HDBT',
    category: 'Presentation Switcher',
    description: '4-input multiview switcher, allows combining NHD-500 series streams for video wall applications.',
    dealerPrice: 900,
    msrp: 1800,
    tags: ['switcher', 'multiview', 'silver'],
  },
  {
      sku: 'SYN-TOUCH10',
      name: 'Synergy 10" Touch Panel',
      category: 'Control',
      description: '10-inch capacitive touch panel for room control. Requires Synergy software.',
      dealerPrice: 850,
      msrp: 1700,
      tags: ['control', 'touchpanel', 'gold'],
      control: { cec: true },
  },
  {
    sku: 'NHD-CTL-PRO-V2',
    name: 'Pro Controller for NetworkHD Series',
    category: 'AVoIP',
    description: 'Centralized controller for NetworkHD systems.',
    dealerPrice: 470,
    msrp: 940,
    tags: ['avoip', 'controller', 'gold']
  }
];
